apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-pqc-security
resources:
  - namespace.yaml
  - storage.yaml
  - mysql.yaml
  - applications.yaml
  - network-policy.yaml

